development:
  adapter: postgresql
  database: twitter004_development
  pool: 5
  timeout: 5000
  username: postgres
  password: admin

test:
  adapter: postgresql
  database: twitter004_test
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
production:
  adapter: postgresql
  database: twitter004_production
  pool: 5
  timeout: 5000
  username: postgres
  password: admin